url: https://y7kim.github.io
baseurl: /newsetu/

# Site settings
title: SETU Stage Ensemble Theater Unit
email: your-email@domain.com
description: "A non-profit English theater group in the Boston area with a mission to build bridges between Indian and Western cultures."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Subrata Das
  pic: team1_subratadas
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Janique Choux Das
  pic: team2_janique
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Je-Kori Salmon
  pic: team4_jekori
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Dhanashree Dontknow 
  pic: team3_dhanashree
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Sushil Motwani
  pic: team5_sushilmotwani
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Yogita Dontknow
  pic: team6_yogita
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Dhanashree Dontknow TODO boy
  pic: team3_dhanashree
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Dhanashree Dontknow TODO girl
  pic: team3_dhanashree
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Dhanashree Dontknow TODO boy
  pic: team3_dhanashree
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://www.facebook.com/SETU-Stage-Ensemble-Theater-Unit-167810514523/
  - title: facebook
    url: https://www.facebook.com/SETU-Stage-Ensemble-Theater-Unit-167810514523/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty